name: Melon Ticket Actions

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '*/2 * * * *'  # 每2分钟运行一次

jobs:
  ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: yarn install
        
      - name: Run Ticket Action
        env:
          MELON_ID: ${{ secrets.MELON_ID }}
          MELON_PW: ${{ secrets.MELON_PW }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          PRODUCT_ID: "211290"  # 替换为实际的演出ID
          PLAY_SEQUENCE: "1"  # 场次序号
          QUANTITY: "2"  # 购票数量
          PREFERRED_SEAT_ZONE_IDS: ""  # 座位区域ID，可选
        run: yarn start
